using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using OpenShop_X.Models.Payments;
using System;
using System.Collections.Generic;

namespace OpenShop_X.Models.Orders
{
    /// <summary>
    /// Represents the entire order, including details such as sub-orders, payment information, seller, and status.
    /// </summary>
    public class Order
    {
        /// <summary>
        /// The primary key of the order, generated by MongoDB.
        /// </summary>
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }

        /// <summary>
        /// Additional metadata related to the order.
        /// </summary>
        public ExtraInfo Extra { get; set; }

        /// <summary>
        /// Basic order information such as creation date and time.
        /// </summary>
        public OrderInfo OrderInfo { get; set; }

        /// <summary>
        /// Payment-related information for the order.
        /// </summary>
        public PayInfo PayInfo { get; set; }

        /// <summary>
        /// Status information about the order.
        /// </summary>
        public StatusInfo StatusInfo { get; set; }

        /// <summary>
        /// A list of sub-orders that are part of this order.
        /// </summary>
        public List<SubOrder> SubOrders { get; set; }

        /// <summary>
        /// Operations that can be performed on the order.
        /// </summary>
        public List<Operation> Operations { get; set; }

        /// <summary>
        /// Trade-related operations for the order.
        /// </summary>
        public List<TradeOperation> TradeOperations { get; set; }
    }
}
